---
# tasks file for ansible-haproxy
- include: debian.yml
  tags:
    - haproxy
  when: ansible_os_family == "Debian"

- include: redhat.yml
  tags:
    - haproxy
  when: ansible_os_family == "RedHat"

- include: opensuse.yml
  when: ansible_os_family == "openSUSE Leap"

- include: config_haproxy.yml
  tags:
    - config_haproxy
    - haproxy
  when: >
        haproxy_config is defined and
        haproxy_config

- name: Allowing Running HAProxy Instances To Bind To A VIP For Failover
  sysctl:
    name: "net.ipv4.ip_nonlocal_bind"
    value: 1
    state: "present"
    reload: yes
  become: true
